[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "22"  
  NPM_VERSION = "10"    

[dev]
  command = "hexo server"  
  publish = "public"       

[[redirects]]
  from = "/gemini/*"
  to = "https://generativelanguage.googleapis.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/u/7Dk4Z"
  to = "https://proxy.mengze.vip/blm"
  status = 200

[[redirects]]
  from = "/install"
  to = "https://cdn.mengze.vip/gh/YShenZe/MengZe-Tool-Pro@main/mengze-tool-pro.user.js"
  status = 301
  force = true

[[redirects]]
  from = "/turbofely"
  to = "https://unpkg.com/turbofely@1.0.0/src/turbofely.js"
  status = 200

[[redirects]]
  from = "/turbofely/demo"
  to = "https://unpkg.com/turbofely@1.0.0/demo/index.html"
  status = 200

[[headers]]
  for = "/rss2.html"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

    [headers.values.OPTIONS]
      Access-Control-Max-Age = "86400"