[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "22"  
  NPM_VERSION = "10"    

[dev]
  command = "hexo server"  
  publish = "public"       

[[redirects]]
  from = "/gemini/*"
  to = "https://generativelanguage.googleapis.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/install"
  to = "https://cdn.mengze.vip/gh/YShenZe/MengZe-Tool-Pro@main/mengze-tool-pro.user.js"
  status = 301
  force = true